name: CD Dev

on:
  push:
    branches: [dev]

jobs:
  apply-dev:
    name: "Apply (dev)"
    uses: ./.github/workflows/_terraform.yml
    with:
      environment: dev
      command: apply
      working-directory: envs/dev
      use-environment: true
